### ISSUE TITLE
Can't find Raspberry_pi section (rpi gpio ) in node-red after an update

### ISSUE THREAD

**Issue by kraeml** [node-red/raspbian-deb-package#2]
After running `update-nodejs-and-nodered` I coldn't find the Rasspberry Pi GPIO Section.

Ther is an stackvoerflow task [here](http://stackoverflow.com/questions/43858438/cant-find-raspberry-pi-section-rpi-gpio-in-node-red-after-an-update?newreg=24cfc05483fe4bd9842b34dde2fe0224):

The python gpio is installed I could not find an error.

The same issue is [here](https://github.com/node-red/node-red-nodes/issues/313). I think here it is better.

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red` (which you've already done). That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!
