### ISSUE TITLE
Node-RED is not yet fully installed  Fetching Node-RED update.

### ISSUE THREAD

**Issue by tannad** [node-red/raspbian-deb-package#7]
Hi ,

Node red was successfully installed with instructions on readme.md but whenever I try to tart node-red it says "Node-RED is not yet fully installed

Fetching Node-RED update.
" 

Even after successful update ,when I try to start it again it still gives the same message. It seems to go in the loop of trying to fetch node-red update. 

Can you kindly help?

Many thanks,
D Tanna

**Comment by knolleary** [comment]
Hi, thanks for raising an issue.

If you check out our [contribution guidelines](https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md) you'll see we prefer to handle this sort of thing on the [mailing list](https://groups.google.com/forum/#!forum/node-red), [slack team](https://nodered.org/slack) or you could ask a question on [Stack Overflow](https://stackoverflow.com/questions/tagged/node-red) and tag it `node-red`. That way the whole Node-RED user community can help, rather than rely on the core development team.

Thanks!

**Comment by AhmadSalmanKhan** [comment]
same issue as tannad.

**Comment by dceejay** [comment]
closing as should now be fixed...
re-open if not

**Comment by SebDominguez** [comment]
I'm having the same problem on a Raspberry Pi 3B+ on a fresh install of Raspbian Stretch Lite.
